CREATE DATABASE Student_Records;
USE Student_Records;
CREATE TABLE Student_Information (StudentID int(20), First_Name varchar(35), Middle_Inital varchar(3), 
Last_Name varchar(35), Program varchar(50), GPA varchar(5));
describe Student_Information;
INSERT INTO Student_Information values(1611321, 'Shayna','D','Willis','BS Computer Science','4.0');
INSERT INTO Student_Information values(1173214, 'Chris','L','Lockhart','BS Accounting','2.5');
INSERT INTO Student_Information values(1234567, 'Lilly','T','Sidney','BS Biology','3.9');
INSERT INTO Student_Information values(2355997, 'Timothy','C','Harris','AS Business Admin','3.5');
INSERT INTO Student_Information values(2455759, 'Kelly','B','Lane','AS Computer Science','3.7');
INSERT INTO Student_Information values(1788920, 'William','L','Turner','BS Criminal Justice','4.0');
INSERT INTO Student_Information values(3924687, 'Susan','P','Baller','MS Cyber Security','4.0');
INSERT INTO Student_Information values(3942867, 'Jessica','Q','Glover','AS Data Analytics','3.1');
INSERT INTO Student_Information values(3943732, 'Scott','A','Rodgers','BA Education','2.1');
INSERT INTO Student_Information values(1007777, 'Kristine','V','Voss','MA English','4.0');
INSERT INTO Student_Information values(1100332, 'Matthew','E','Carter','BA History','2.9');
INSERT INTO Student_Information values(1144556, 'Dolly','P','Tennesse','MS Marketing','4.0');
SELECT * FROM Student_Information;
UPDATE Student_Information SET Last_Name='Clark' WHERE First_Name = 'Kelly';
SELECT * FROM Student_Information;
UPDATE Student_Information SET GPA = '3.0' WHERE Last_Name = 'Rodgers';
UPDATE Student_Information SET Program = 'BS Information Technology' WHERE Last_Name = 'Rodgers';
SELECT * FROM Student_Information WHERE Last_Name = 'Rodgers';
SELECT * FROM Student_Information WHERE Program  = 'BS Computer Science';
SELECT * FROM Student_Information WHERE GPA = '4.0';
SELECT * FROM Student_Information ORDER BY Program ASC;
SELECT First_Name FROM Student_Information WHERE GPA ='4.0' AND GPA = '3.9';
SELECT First_Name FROM Student_Information WHERE GPA ='4.0' AND Program = 'MS Cyber Security';
DELETE FROM Student_Information WHERE Middle_Inital = 'T';
DELETE FROM Student_Information WHERE Middle_Inital = 'L';
SELECT * FROM Student_Information;
